# Generated by Django 6.0.2 on 2026-03-01 05:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
                ('symptoms', models.TextField()),
                ('onset_time', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-arrival_time'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecg_findings', models.JSONField(null=True)),
                ('biomarker_findings', models.JSONField(null=True)),
                ('imaging_findings', models.JSONField(null=True)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('CRITICAL', 'Critical'), ('INCONCLUSIVE', 'Inconclusive')], max_length=20)),
                ('final_report', models.TextField()),
                ('confidence_score', models.FloatField()),
                ('recommended_actions', models.JSONField(null=True)),
                ('retrieved_guidelines', models.TextField(null=True)),
                ('loop_count', models.IntegerField(default=0)),
                ('agent_agreement', models.BooleanField(default=True)),
                ('discordant_agents', models.JSONField(default=list)),
                ('doctor_confirmed', models.BooleanField(default=False)),
                ('doctor_override', models.BooleanField(default=False)),
                ('doctor_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time_seconds', models.FloatField(null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='emergency.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecg_file', models.FileField(blank=True, null=True, upload_to='ecg_uploads/')),
                ('xray_file', models.ImageField(blank=True, null=True, upload_to='xray_uploads/')),
                ('troponin', models.FloatField()),
                ('bnp', models.FloatField()),
                ('ldl', models.FloatField()),
                ('hba1c', models.FloatField()),
                ('creatinine', models.FloatField()),
                ('ckmb', models.FloatField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='emergency.patient')),
            ],
        ),
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency.patient')),
            ],
        ),
    ]
