# Generated by Django 5.2.1 on 2026-03-08 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CeleryTask',
        ),
    ]
