# Generated by Django 5.2.1 on 2026-03-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_delete_celerytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticinput',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticinput',
            name='systolic_bp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
