# Generated by Django 5.2.1 on 2026-03-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_diagnosticinput_heart_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticinput',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='report_uploads/'),
        ),
        migrations.AlterField(
            model_name='diagnosticinput',
            name='bnp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosticinput',
            name='creatinine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosticinput',
            name='hba1c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosticinput',
            name='ldl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosticinput',
            name='troponin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='onset_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
