# Generated by Django 5.2.1 on 2026-03-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0004_diagnosticinput_report_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticinput',
            name='xray_file',
        ),
        migrations.AddField(
            model_name='diagnosticinput',
            name='echo_file',
            field=models.ImageField(blank=True, null=True, upload_to='echo_uploads/'),
        ),
    ]
