# Generated by Django 5.2.1 on 2026-03-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0005_rename_xray_to_echo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticinput',
            name='echo_file',
            field=models.FileField(blank=True, null=True, upload_to='echo_uploads/'),
        ),
    ]
